<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Agents.Persistent" Version="1.1.0" />
    <PackageReference Include="Azure.Identity" Version="1.13.2" />
  </ItemGroup>

</Project>
